# Generated by Django 5.0.6 on 2024-05-14 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_alter_campaign_end_date_alter_campaign_start_date_and_more'),
        ('vaccination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='slot',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='slots',
            field=models.ManyToManyField(blank=True, related_name='slots', to='camp.slot'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='camp.campaign'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='updated_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
