# Generated by Django 5.0.6 on 2024-05-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='adress',
            new_name='address',
        ),
    ]
